import { describe, expect, it, vi, beforeEach } from "vitest";

// ============================================================
// Adversarial tests generated by /challenge project sweep
// Targets: auth, rate-limit bypass, input validation, RAG thresholds
// ============================================================

// --- 1. extractMessageText boundary tests ---

import { extractMessageText } from "@/lib/chat/message-utils";

describe("extractMessageText — adversarial inputs", () => {
	it("returns empty string for undefined content and undefined parts", () => {
		expect(extractMessageText({})).toBe("");
	});

	it("returns empty string for empty parts array", () => {
		expect(extractMessageText({ parts: [] })).toBe("");
	});

	it("ignores parts with non-text type", () => {
		expect(
			extractMessageText({
				parts: [
					{ type: "image", text: "ignored" },
					{ type: "tool_call", text: "also ignored" },
				],
			}),
		).toBe("");
	});

	it("prefers content over parts when both present", () => {
		expect(
			extractMessageText({
				content: "from content",
				parts: [{ type: "text", text: "from parts" }],
			}),
		).toBe("from content");
	});

	it("handles parts with text type but undefined text", () => {
		expect(
			extractMessageText({
				parts: [{ type: "text" }],
			}),
		).toBe("");
	});

	it("concatenates multiple text parts without separator", () => {
		expect(
			extractMessageText({
				parts: [
					{ type: "text", text: "hello" },
					{ type: "text", text: " world" },
				],
			}),
		).toBe("hello world");
	});
});

// --- 2. getClientIp spoofing tests ---

import { getClientIp } from "@/lib/request-utils";

describe("getClientIp — IP spoofing vectors", () => {
	function makeRequest(headers: Record<string, string>, ip?: string) {
		const h = new Headers(headers);
		const req = new Request("http://localhost/api/chat", { headers: h });
		if (ip) {
			Object.defineProperty(req, "ip", { value: ip });
		}
		return req;
	}

	it("prefers request.ip over x-forwarded-for", () => {
		const req = makeRequest({ "x-forwarded-for": "spoofed" }, "real-ip");
		expect(getClientIp(req)).toBe("real-ip");
	});

	it("trusts first x-forwarded-for value when request.ip is absent", () => {
		const req = makeRequest({ "x-forwarded-for": "attacker, proxy1, proxy2" });
		// This test documents the current (vulnerable) behavior
		expect(getClientIp(req)).toBe("attacker");
	});

	it("falls back to 127.0.0.1 when no IP source is available", () => {
		const req = makeRequest({});
		expect(getClientIp(req)).toBe("127.0.0.1");
	});

	it("returns arbitrary value from x-forwarded-for without validation", () => {
		const req = makeRequest({ "x-forwarded-for": "not-an-ip" });
		// Documents that no IP format validation exists
		expect(getClientIp(req)).toBe("not-an-ip");
	});
});

// --- 3. context-builder boundary tests ---

import {
	calculateAvailableBudget,
	selectHistoryMessages,
	MAX_INPUT_TOKENS,
} from "@/lib/chat/context-builder";

describe("calculateAvailableBudget — edge cases", () => {
	it("returns negative budget when system + RAG exceed max", () => {
		const result = calculateAvailableBudget(100_000, 50_000);
		expect(result).toBe(MAX_INPUT_TOKENS - 150_000);
		expect(result).toBeLessThan(0);
	});

	it("returns full budget for zero-token inputs", () => {
		expect(calculateAvailableBudget(0, 0)).toBe(MAX_INPUT_TOKENS);
	});
});

describe("selectHistoryMessages — budget constraints", () => {
	it("returns empty array for empty messages", () => {
		expect(selectHistoryMessages([], 1000)).toEqual([]);
	});

	it("keeps minimum 2 messages even when over budget", () => {
		const messages = [
			{ role: "user", content: "a".repeat(10000) },
			{ role: "assistant", content: "b".repeat(10000) },
			{ role: "user", content: "c".repeat(10000) },
		];
		// With a tiny budget, should still keep 2
		const result = selectHistoryMessages(messages, 1);
		expect(result.length).toBe(2);
	});

	it("handles negative budget gracefully (keeps minimum 2)", () => {
		const messages = [
			{ role: "user", content: "hello" },
			{ role: "assistant", content: "world" },
		];
		const result = selectHistoryMessages(messages, -100);
		// Budget is negative, but minimum 2 messages are kept
		expect(result.length).toBe(2);
	});
});

// --- 4. tenant-id determinism tests ---

import { getTenantIdFromIp } from "@/lib/sandbox/tenant-id";

describe("getTenantIdFromIp — tenant isolation", () => {
	it("produces deterministic output for same IP", () => {
		const a = getTenantIdFromIp("192.168.1.1");
		const b = getTenantIdFromIp("192.168.1.1");
		expect(a).toBe(b);
	});

	it("produces different output for different IPs", () => {
		const a = getTenantIdFromIp("192.168.1.1");
		const b = getTenantIdFromIp("192.168.1.2");
		expect(a).not.toBe(b);
	});

	it("handles empty string IP (fallback scenario)", () => {
		// If getClientIp somehow returns empty, tenant ID should still be valid
		const result = getTenantIdFromIp("");
		expect(result).toMatch(/^tenant_[a-f0-9]{12}$/);
	});

	it("handles IPv6 addresses", () => {
		const result = getTenantIdFromIp("::1");
		expect(result).toMatch(/^tenant_[a-f0-9]{12}$/);
	});
});

// --- 5. cost-tracking alert threshold boundary tests ---

vi.mock("@upstash/redis", () => ({
	Redis: {
		fromEnv: () => ({}),
	},
}));

import { checkCostAlerts, DAILY_BUDGET } from "@/lib/cost-tracking";

describe("checkCostAlerts — adversarial boundary values", () => {
	it("handles NaN input", () => {
		const result = checkCostAlerts(Number.NaN);
		// NaN comparisons are all false, so all thresholds fail, returns 'ok'
		expect(result.level).toBe("ok");
	});

	it("handles negative cost", () => {
		const result = checkCostAlerts(-5);
		expect(result.level).toBe("ok");
	});

	it("handles Infinity", () => {
		const result = checkCostAlerts(Number.POSITIVE_INFINITY);
		expect(result.level).toBe("shutoff");
	});

	it("handles very small positive number", () => {
		const result = checkCostAlerts(0.0001);
		expect(result.level).toBe("ok");
	});
});

// --- 6. extractDocumentTitle boundary tests ---

import { extractDocumentTitle } from "@/lib/documents/upload";

describe("extractDocumentTitle — edge cases", () => {
	it("uses titleOverride when provided", () => {
		expect(extractDocumentTitle("# Heading", "file.md", "Override")).toBe(
			"Override",
		);
	});

	it("extracts first markdown heading when no override", () => {
		expect(extractDocumentTitle("# My Title\n\nContent", "file.md")).toBe(
			"My Title",
		);
	});

	it("falls back to filename stem when no heading", () => {
		expect(extractDocumentTitle("No headings here", "document.txt")).toBe(
			"document",
		);
	});

	it("handles empty content with filename fallback", () => {
		expect(extractDocumentTitle("", "report.pdf")).toBe("report");
	});

	it("trims whitespace-only titleOverride and falls through", () => {
		expect(extractDocumentTitle("# Real Title", "file.md", "   ")).toBe(
			"Real Title",
		);
	});

	it("handles file without known extension", () => {
		expect(extractDocumentTitle("no heading", "weirdfile")).toBe("weirdfile");
	});
});

// --- 7. chunker boundary tests ---

import { chunkMarkdown } from "@/lib/embeddings/chunker";

describe("chunkMarkdown — adversarial inputs", () => {
	it("returns empty array for empty content", () => {
		expect(chunkMarkdown({ title: "Test", content: "" })).toEqual([]);
	});

	it("returns empty array for whitespace-only content", () => {
		expect(chunkMarkdown({ title: "Test", content: "   \n\n  " })).toEqual([]);
	});

	it("handles content with only code blocks (no headings)", () => {
		const content = "```js\nconsole.log('hello');\n```";
		const chunks = chunkMarkdown({ title: "Test", content });
		// Should produce at least one chunk under 'General' heading
		for (const chunk of chunks) {
			expect(chunk.sectionHeading).toBe("General");
		}
	});

	it("does not split inside code blocks on ## headings", () => {
		const content = [
			"## Real Section",
			"Some content",
			"```markdown",
			"## This is inside a code block",
			"```",
			"More content",
		].join("\n");
		const chunks = chunkMarkdown({ title: "Test", content });
		// Should only have one section "Real Section", not two
		const headings = chunks.map((c) => c.sectionHeading);
		expect(headings).not.toContain("This is inside a code block");
	});

	it("assigns correct position and totalChunks metadata", () => {
		const content = "## A\nContent A\n\n## B\nContent B\n\n## C\nContent C";
		const chunks = chunkMarkdown({
			title: "Test",
			content,
			// Use low minChunkTokens to ensure all sections are kept
		});
		if (chunks.length > 0) {
			expect(chunks[0].position).toBe(1);
			expect(chunks[chunks.length - 1].position).toBe(chunks.length);
			for (const chunk of chunks) {
				expect(chunk.totalChunks).toBe(chunks.length);
			}
		}
	});
});
